{"name": "test_fail_login[错误的密码]", "status": "passed", "description": "\n        1、错误的密码\n        2、错误的用户\n        :return:1\n        ", "attachments": [{"name": "log", "source": "2e407ff5-a95d-4208-8b33-276b97903de2-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "params", "value": "{'username': '天才儿子', 'password': '111111'}"}], "start": 1647151570742, "stop": 1647151570821, "uuid": "07b0d3a0-e539-4282-bcd9-01b17f1720db", "historyId": "8b24ede942356fb86886f75660256535", "testCaseId": "87acfe5b98e3b3c095c7c4325dbf5b5b", "fullName": "testcases.test_login.TestLogin#test_fail_login", "labels": [{"name": "feature", "value": "异常登录"}, {"name": "story", "value": "错误的密码、用户进行登录"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-L39EMF3A"}, {"name": "thread", "value": "6352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}