{"name": "test_fail_login[错误的密码]", "status": "passed", "description": "\n        1、错误的密码\n        2、错误的用户\n        :return:1\n        ", "attachments": [{"name": "log", "source": "57915319-9cbe-4786-b2b3-19d1e6d61acb-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "params", "value": "{'username': '天才儿子', 'password': '111111'}"}], "start": 1647152295695, "stop": 1647152295794, "uuid": "854fc78f-21d9-429f-97fd-01571eba8c6c", "historyId": "8b24ede942356fb86886f75660256535", "testCaseId": "87acfe5b98e3b3c095c7c4325dbf5b5b", "fullName": "testcases.test_login.TestLogin#test_fail_login", "labels": [{"name": "feature", "value": "异常登录"}, {"name": "story", "value": "错误的密码、用户进行登录"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-L39EMF3A"}, {"name": "thread", "value": "14232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}