{"name": "test_fail_login[错误的密码]", "status": "passed", "description": "\n        1、错误的密码\n        2、错误的用户\n        :return:1\n        ", "attachments": [{"name": "log", "source": "c5b01bd3-6c2f-4807-a4f2-05614f965f63-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "params", "value": "{'username': '天才儿子', 'password': '111111'}"}], "start": 1647154451459, "stop": 1647154451543, "uuid": "51025c5f-7562-421e-965a-5a24a82a74ce", "historyId": "8b24ede942356fb86886f75660256535", "testCaseId": "87acfe5b98e3b3c095c7c4325dbf5b5b", "fullName": "testcases.test_login.TestLogin#test_fail_login", "labels": [{"name": "story", "value": "错误的密码、用户进行登录"}, {"name": "feature", "value": "异常登录"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-L39EMF3A"}, {"name": "thread", "value": "13628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}