{"name": "test_fail_login[错误的密码]", "status": "passed", "description": "\n        1、错误的密码\n        2、错误的用户\n        :return:1\n        ", "attachments": [{"name": "log", "source": "3d830edd-4b91-4ff3-9aca-634eeb6f54d8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "params", "value": "{'username': '天才儿子', 'password': '111111'}"}], "start": 1647158718160, "stop": 1647158718279, "uuid": "3cca6a75-22fb-46e7-868a-603a0c9e1b40", "historyId": "8b24ede942356fb86886f75660256535", "testCaseId": "87acfe5b98e3b3c095c7c4325dbf5b5b", "fullName": "testcases.test_login.TestLogin#test_fail_login", "labels": [{"name": "story", "value": "错误的密码、用户进行登录"}, {"name": "feature", "value": "异常登录"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-L39EMF3A"}, {"name": "thread", "value": "17332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}